replicaCount: 1

image:
  repository: ghcr.io/steph76k/surf-mcp-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: surf-mcp.rke2-cluster1.berger.ph
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  - name: WORLDTIDES_API_KEY
    valueFrom:
      secretKeyRef:
        name: surf-mcp
        key: worldtides-api-key

  - name: SWELLCLOUD_API_KEY
    valueFrom:
      secretKeyRef:
        name: surf-mcp
        key: swellcloud-api-key

spotData:
  configMap:
    enabled: false
    name: ""
